# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung einer LOGO SPS'
        en: 'Control a LOGO PLC'
    maintainer: 'ivande'
    tester: ''                    # Who tests this plugin?
    state: ready
    keywords: LOGO 0BA7 0BA8 PLC SPS libnodave
    documentation: https://www.smarthomeng.de/dev/user/plugins/logo/README.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/36372-plugin-siemens-logo-0ba7

    version: 1.2.4                 # Plugin version
    sh_minversion: 1.2             # minimum shNG version to use this plugin
    #sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: LOGO                # class containing the plugin

parameters:
# Definition of parameters to be configured in etc/plugin.yaml

    io_wait:
        type: int
        default: 5
        valid_min: 1
        valid_max: 600
        description:
            de: 'Zeit zwischen zwei Leseanforderungen'
            en: 'time period between two read requests'

    host:
        type: ip
        default: ''
        description:
            de: 'IP-Adresse oder Hostname der LOGO'
            en: 'Hostname or ip address of the LOGO'

    port:
        type: int
        default: 102
        valid_min: 0
        valid_max: 65535
        description:
            de: 'Kommunikationsport der LOGO'
            en: 'Communication port used by LOGO'

    version:
        type: str
        default: '0BA7'
        valid_list:
          - '0BA7'
          - '0BA8'
        description:
            de: 'Hardware Version der LOGO'
            en: 'Hardware version of the LOGO'

item_attributes:
    # Definition of item attributes defined by this plugin

    logo_read:
        type: str
        description:
            de: "Lesebefehl für die LOGO SPS"
            en: "Read command for the LOGO PLC"
    logo_write:
        type: str
        description:
            de: "Schreibbefehl für die LOGO SPS"
            en: "Write command for the LOGO PLC"


item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

